### ISSUE TITLE
標準偏差を求めてみよう

### ISSUE THREAD

**Issue by YoshiyukiItoh** [yuki-kimoto/perlzemidatascience#10]

**Comment by yuki-kimoto** [comment]
chart.jsでのグラフ化という課題をこちらに追加しておきますね。

**Comment by YoshiyukiItoh** [comment]
以下のような構成を想定しています。
1ブロック目
　いつものように標準偏差を求めるサンプル
2ブロック目
　chart.jsを用いたグラフ化
　データは検討中

**Comment by YoshiyukiItoh** [comment]
一旦クローズします。
