### ISSUE TITLE
平均値を求めてみよう

### ISSUE THREAD

**Issue by YoshiyukiItoh** [yuki-kimoto/perlzemidatascience#5]

**Comment by YoshiyukiItoh** [comment]
夜遅かったため、今ご連絡します。
ご確認お願いいたします！
https://github.com/yuki-kimoto/perlzemidatascience/pull/6

**Comment by yuki-kimoto** [comment]
ありがとう! マージします!

**Comment by yuki-kimoto** [comment]
トップページから記事へのリンクを張っていただくことは可能でしょうか?

**Comment by YoshiyukiItoh** [comment]
リンクを貼りました。合わせて誤記の修正も行いました。
https://github.com/yuki-kimoto/perlzemidatascience/pull/7
